const Hindi = {
	Preface: 'çLrkouk',
	Foreword: 'çkDdFku',
	Reviews: `leh{kk`,
	Author: `ys[kd&ifjp;`,
	Anjesh: `अञ्जेश`,
	Baranwal: `बरनवाल`,
	Introduction: `gekjk bfrgkl gekjs Hkfo"; dh 
	vk/kkjf'kyk gS vkSj bfrgkl ftruk vf/kd lR; gksxk] Hkfo"; dh fn'kk mruh gh Li"V gksxhA dkYifud dFkk ds ek/;e ls _XoSfnd dky dks m)\`r djus dk ç;kl gS rhu [k.Mksa dh miU;kl la xPN/oe~A`,
	PrefaceContent: `nSo&çsfjr çkjEHk gqvk vkRe&fpUru vkSj mlds ifj.kke Lo:i ,d çsj.kk] ,d ,slh çsj.kk] ftlus lekt dks okil dqN nsus dk ladYi ysus dks foo'k fd;kA lekt dks dqN nsus ds fo"k; ij tc eSaus euu djuk çkjEHk fd;k rks vusd çdkj ds ldkjkRed o udkjkRed fopkjksa ds lkFk gh lkFk vusd çdkj ds nqfo/kkvksa us Hkh eu dks ?ksjk vkSj eu /khjs&/khjs eu dqUn Hkh gqvkA ij bu lHkh fopkjksa vkSj nqfo/kkvksa ds chp tc lkeus viuh vxyh ih<+h ij –f"V xbZ rks eu ds lHkh fopkj ,dkaxh gks x, vkSj lHkh nqfo/kk,¡ foyksfir gksus yxhaA 
	lkeus [kM+h bl ubZ ih<+h dk ykyu&ikyu ,dy&ifjokj esa vkSj f'k{kk&nh{kk vaxzsth ek/;e ds fo|ky;ksa esa gks jgh FkhA ;g bl feêh dh ijEijkvksa ds ckjs esa flQZ mruk gh tku ik jgh Fkh] ftlls fd cl bldk dke py tk jgk FkkA ;g ih<+h bl feêh dh ijEijkvksa dh okgd cu ldsxh] blesa eq>s lUnsg fn[kkA bUgha fopkjksa ds lkFk esjh –f"V tc bl ih<+h ij iM+h rks bl fØ;k dh çfrfØ;k us eq>s Lo;a vius Hkhrj Hkh >k¡dus ds fy, iqu% ,d ckj foo'k fd;kA bl iwjs ?kVukØe ij lexz :i ls tc –f"Vikr fd;k rks ekuks esjs  iSjksa ds uhps ls tehu gh f[kld xbZA eSa Lo;a dgk¡ [kM+k Fkk] ;g ns[kdj eSa nax jg x;kA ,slk dHkh lkspk Hkh ugha FkkA vxyh ih<+h rks D;k] esjh Lo;a dh fLFkfr Hkh buls dqN fo'ks"k fHkUu ugha feyhA jk"Vªdfo eSfFkyh 'kj.k xqIr dh os iafä;ka esjs eu esa dkSa/k xbZa] tks dgrh gSa]
	
	"ftldks u fut xkSjo] u fut ns'k dk vfHkeku gS]
	og uj ugha] fujk i'kq vkSj e\`rd leku gSA"
	
	jk"Vªdfo dh bu iafä;ksa esa fufgr lans'k dks vxzlkfjr djuk rks nwj] mls vkRelkr djus esa ge Lo;a Hkh fiNM+rs gq, fn[kkbZ ns jgs Fksa] dkj.k pkgs tks Hkh gksA Qyr% bl deh dh HkjikbZ djus ds rjhds ij fopkj djrs gq, eSaus vius ladYi dks ,d vk;ke fn;k vkSj fu.kZ; fy;k fd fo'o dh çkphure thfor ekuo lH;rk ds çkphure miyC/k xzaFk vFkkZr~ _Xosn ls igys Lo;a dks] vkSj rRi'pkr vU; lkekU; tuksa dks Hkh ifjfpr djkus dh fn'kk esa ç;kl fd;k tkuk pkfg,A
	
	ladYi dh fn'kk fu/kkZfjr gks pqdh Fkh vkSj vc bl fn'kk esa dne c<+kus dh ckjh FkhA ladYi Fkk viuh lkaL—frd ijEijkvksa ds ewy vFkkZr~ _Xosn dk v/;;u djuk vkSj blds lans'kksa dks fdlh uk fdlh ek/;e ls çlkfjr djukA bl ladYi dks ewrZ:i nsus dh fn'kk esa çFke pj.k ds :i esa _Xosn lafgrk dh O;oLFkk dj mldk Lok/;k; çkjEHk dj fn;kA 
	
	v/;;u tSls&tSls vkxs c<+rk x;k] _Xosn vkSj _XoSfnd dky ds ckjs esa fur ubZ vkSj vpfEHkr djus okyh tkudkfj;k¡ lkeus vkus yxhaA esjs v/;;u esa] tSlk eSaus ik;k] _Xosn eq[; :i ls ,sls eU=ksa dk laxzg gS ftudh jpuk ;K ds le; fofHkUu nsoksa dks çlUu djus ds fy, dh xbZ FkhA u gh ;g ml dky&[k.M dk dksbZ dkO; Fkk vkSj u gh bldh jpuk ml dky&[k.M dh thou&i)fr dks fo'ysf"kr djus ds fy, dh xbZ FkhA fdUrq ,slk Hkh ugha fd bu eU=ksa ds vk/kkj ij ml dky&[k.M ds jgL;ksa dks mn~?kkfVr ugha fd;k tk ldrk gksA bu eU=ksa esa gh nsoksa dh ç'kalk djrs le; vyx&vyx ,slh vusd fc[kjh gqbZ ?kVuk,¡] fopkj vkSj lans'k of.kZr gSa ftudk Js; mu nsoksa dks fn;k x;k gS] rFkk bu ?kVukvksa] fopkjksa vkSj lans'kksa dh ;kn fnykrs gq, mu nsoksa dk ckjEckj vkºoku fd;k x;k gSA bl çdkj ls of.kZr ?kVukvksa] fopkjksa vkSj lans'kksa dk fo'ys"k.k tc esjs }kjk vius lkeus fo|eku vkt Hkh çpfyr viuh ijEijkvksa ds vk/kkj ij fd;k x;k rks ;g fopkj iq"V gks x;k fd _Xosn dk dky&[k.M çR;sd –f"V ls ,d fodflr dky&[k.M Fkk vkSj bl dky&[k.M ds fo"k; esa eu esa fo|eku vusd HkzkfUr;k¡ Hkh nwj gksus yxhaA bl v/;;u ds ifj.kke Lo:i fur u, mn~?kkfVr jgL;ksa us esjs ladYi dks vkSj Hkh –<+rk çnku dj nh D;ksafd bl /kjrh ij fo|eku çkphure thfor ekuo lH;rk ds bl çkphure xzUFk esa of.kZr ?kVukvksa] fopkjksa vkSj lans'kksa dks çlkfjr fd;k tkus dk mís'; esjs vUreZu esa vc vkSj Hkh Li"V gks pqdk FkkA
	
	ijUrq okLrfod pqukSrh vHkh vkuh 'ks"k Fkh] vkSj og Fkh fd _Xosn ds lans'kksa dks fdl :i esa vkSj fdl ek/;e ls lekt ds lkeus çLrqr fd;k tk, ftlls bldh igq¡p vf/kdre gks ldsA bl fo"k; ij vUreZu esa pys fujUrj eUFku us vUrr% ;g Hkh fu/kkZfjr djk fn;k vkSj esjs }kjk ;g fu.kZ; fy;k x;k fd _Xosn esa of.kZr ?kVukvksa] fopkjksa vkSj lans'kksa dks ,d dgkuh ds :i esa çLrqr fd;k tkuk gh loksZÙke fodYi gksxkA vius bl fu.kZ; vkSj ladYi dks iw.kZ djus dh fn'kk esa vkxs c<+us ds mís'; ls esjs }kjk _Xosn esa of.kZr vusd ?kVukvksa] fopkjksa vkSj lans'kksa dk p;u djrs gq, mUgsa ,d dkYifud dkykuqØe esa latksus dh çfØ;k dk ç;kl vkjEHk dj fn;k x;kA
	
	bl fu;ksftr fn'kk esa py jgs esjs vuojr v/;;u vkSj bl dgkuh ds Lo:i ds fu/kkZj.k dh çfØ;k ds nkSjku gh _Xosn esa of.kZr ,d ,sls uxj dk uke lkeus ls xqtjk ftlus esjs eu dks dkQh xgjkbZ ls >d>ksj dj j[k fn;k] D;ksafd ;g uke Lo;a gh tksj&tksj ls iqdkj dj dqN lUns'k ns jgk FkkA bl uxj dk uke rFkkdfFkr ^flU/kq ?kkVh dh lH;rk* ds ,d egÙoiw.kZ uxj ds uke ls fcYdqy gh esy [kkrk gqvk FkkA bl uxj ds uke us dqN ,slh fn'kk esa fopkj djus ij foo'k dj fn;k] ftl fn'kk esa dHkh Hkh dksbZ ppkZ fdlh lkoZtfud eap ij] de ls de esjs }kjk] ugha lquh xbZ FkhA  
	
	^flU/kq ?kkVh dh lH;rk* dk ifjp; ftl çdkj ls ges djk;k tkrk jgk gS] mlds vk/kkj ij eu esa bldh ,slh Nfo fufeZr gS tSls fd ;g lH;rk gekjs iwoZtksa ls lEcfU/kr u gksdj ,d ,slh vtuch lh lH;rk Fkh tks fd vius le; ls dkQh vkxs Fkh vkSj ;g lH;rk nqHkkZX;o'k vdLekr~ gh foyqIr Hkh gks xbZA bl lH;rk dk fo"k; eu ds fdlh dksus esa lnSo ls gh ,d igsyh ds :i esa iM+k gqvk Fkk vkSj bl uxj ds uke esa lEHkor% ml igsyh dk mÙkj fNik gqvk çrhr gksus yxkA 
	
	eSaus viuh iqjk.kh ikBî&iqLrdksa dks [kaxkyuk çkjEHk fd;k vkSj ik;k fd muds vuqlkj] flU/kq ?kkVh dh lH;rk vkSj oSfnd lH;rk yxHkx ledkyhu gSa rFkk mudk HkkSxksfyd foLrkj Hkh yxHkx leku gSA FkksM+k vkSj ns[kus ij ;g Hkh irk pyrk gS fd ,d vksj flU/kq ?kkVh dh lH;rk dk o.kZu dsoy iqjkrkfÙod lk{;ksa ds vk/kkj ij fd;k tkrk gS] tcfd nwljh vksj oSfnd lH;rk dk o.kZu dsoy lkfgfR;d lk{;ksa vFkkZr~ osnksa ds vk/kkj ij fd;k tkrk gSA _XoSfnd uxj ds bl uke us esjh dYiukvksa dks tSls ia[k yxk fn, vkSj esjh dgkuh dks ,d mís'; ns fn;k] vkSj ,dne ls gh bl dgkuh ds ys[ku dk dk;Z çkjEHk gks x;kA 
	
	rhu [k.Mksa esa foHkkftr ,d lexz miU;kl ds :i esa fyf[kr ;g dgkuh _Xosn esa of.kZr vusd ?kVukvksa] fopkjksa vkSj lans'kksa ij vk/kkfjr gSA blds ys[ku esa ;g ç;kl jgk gS fd _XoSfnd dky ls lEcfU/kr vusdksa HkzkfUr;ksa ds laca/k esa viuk i{k j[kus ds lkFk gh lkFk rRdkyhu lkekftd] vkfFkZd] jktuhfrd o lkaL—frd ifjfLFkfr;ksa ls ikBd dk ifjp; djk;k tk ldsA oSfnd lH;rk ls fHkUu rFkkdfFkr ^flU/kq ?kkVh dh lH;rk* ds feFkd ds ckjs esa Hkh ikBd fopkj dj ldsa vkSj bl fo"k; ij lkoZtfud eapksa ij ppkZ vkxs c<+ lds] 'k\`a[kyk ds mÙkjk/kZ esa ;g Hkh ç;kl fd;k x;k gSA
	
	mi;qZä Hkkouk] ladYi] mís'; vkSj ç;kl dks vius vki esa l¡tks, ^la xPN/oE* 'k\`a[kyk dk çFke [k.M ^flU/kq rV dk vuke xk¡o* bl fo'okl ds lkFk çLrqr gS fd bls ikBdksa dk Hkjiwj Lusg feysxkA ikBdksa dks ;g Hkh voxr djkuk pkgw¡xk fd çLrqr çFke [k.M esa lglzksa o"kZ iwoZ dh ml thoUr lH;rk ls lacaf/kr rF; vkSj dYiuk ls fefJr jksek¥~p dh nqfu;k dk dsoy }kj ek= gh [kqyrk gSA çR;sd vkxkeh [k.M bl jksek¥~p dks vkSj Hkh vf/kd c<+krk gh tk,xk] vr% ikBdksa ls fuosnu gS fd _XoSfnd dky dh bl ;k=k esa gekjs lkFk ,d lg;k=h ds :i esa vUr rd tqM+s jgsaA
	`,
};

export default Hindi;
